name: pipeline
version: '1.0.0'
config-version: 2
profile: pipeline

model-paths: ["models"]
macro-paths: ["macros"]

models:
  pipeline:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: silver
