name: pipeline
version: '1.0.0'
config-version: 2
profile: pipeline

model-paths: ["models"]
macro-paths: ["macros"]

models:
  pipeline:
    sales:
      green:
        silver:
          +schema: silver
