services:
  ingest:
    build:
      context: ./services
      no_cache: true
    volumes:
      - ./services/config.yaml:/app/config.yaml
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy

  dbt:
    build:
      context: ./dbt
      no_cache: true
    environment:
      DBT_HOST: postgres
    depends_on:
      ingest:
        condition: service_completed_successfully

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
